language: java
sudo: false

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mutants;'

script:
  - - mvn clean -Dserver.port=8080 jacoco:prepare-agent install jacoco:report

